language: node_js
sudo: false
node_js:
- "5"
cache:
  directories:
  - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g coveralls
script:
- npm run travis
after_success:
  - coveralls < ./coverage/lcov.info
env:
  global:
    secure: "YSPTs2lF23mAXcJqj0WCPrkD3V9xicnQLmA7X39r9yIhRs8SnY1x3CoA5Zp3dRnmU8TArVnyj7z8xNjvglyVbIx2wAFj0yRKs7gaXXrqzO9vo/fGun+t7FUrOyCJhjOjYesYcu8OVvvDVfExgc8GQ1FUbzgD+kxCRS0t4ptW6e/njYjlUr09L7dakL8XPSkxpN20Ym3NKE6mMLAu6GpcbSAfIp5BpRBTlc9R0u0rQfSQjqWqaEuGlQSn2BmR56za5eokPRx3zpSmHAJmb53vRFu0fXUFDK6mRdW7SZmJaQl7shIIYnHAsvMhthwEGGPFSeqchaeqZfYqDSdNgtdKAfLoSOlQHjM+29Umx7o4qNa5etJh5JeZrzlJBh07XSpp9d/eeh1jf4t4alTLgNz5Y5kBckstvNhEZxlAPfIq0nc45K+0qprDyM/c7x1AmkcAduIxdV92ZaXq27a7ZUcjyLW92B333k+gFSkwwacEL0a1EqA5dPvGZ9wSBLOgDXBCtUEuI1ayX71X+6hUoP2Xyl5Tdja/21b195KtQjBzopeK97UQnVuAYsog1K7MInnjn6BRlc0lsI/DcGo38EJENulmToUeY19alYaHppQfbaOoFGumBYT3gms1NYhlC0hGESD9JKT+AAKGCslFN8FRdE2nN8Beyf/TFDu+ReBEkQI="
